---
- name: Exchange Keys between servers
  become: yes
  become_user: pbsadmin
  hosts: all_nodes
  tasks:
    - name: SSH KeyGen command
      tags: run
      shell: > 
        ssh-keygen -q -b 2048 -t rsa -N "" -C "creating SSH" -f ~/.ssh/id_rsa
        creates="~/.ssh/id_rsa"
    - name: Fetch the keyfile from one server to another
      tags: run
      fetch: 
        src: "~/.ssh/id_rsa.pub"
        dest: "/tmp/buffer/{{ansible_hostname}}-id_rsa.pub"
        flat: yes
    - name: Copy the key add to authorized_keys using Ansible module
      tags: run
      authorized_key:
        user: pbsadmin
        state: present
        key: "{{ lookup('file','/tmp/buffer/{{item.dest}}-id_rsa.pub') }}"
      when: item.dest != ansible_hostname
      with_items:
        - { dest: "{{ groups['all_nodes'][0] }}"}
        - { dest: "{{ groups['all_nodes'][1] }}"}
        - { dest: "{{ groups['all_nodes'][2] }}"}